#!/usr/bin/env node
// Builds platform themes from design/tokens/tokens.json (step 2, D-040).
// Style Dictionary parses DTCG and resolves references; each platform has a small explicit template below,
// so the generated code reads like hand-written platform code. Output is committed; CI fails on drift.
//
//   node design/generators/build.mjs          write all outputs
//   node design/generators/build.mjs --check  exit 1 if any output would change
import { mkdirSync, readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const CHECK = process.argv.includes('--check');
const HEADER = 'GENERATED by design/generators/build.mjs from design/tokens/tokens.json. Do not edit.';

const sd = new StyleDictionary({
  source: [join(ROOT, 'design/tokens/tokens.json')],
  usesDtcg: true,
  log: { verbosity: 'silent' },
  platforms: { raw: { transforms: [] } },
});
const t = await sd.exportPlatform('raw');

// ---------- helpers ----------
const v = (node) => node.$value;
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const snake = (s) => s.replace(/-/g, '_');
const leaves = (group) => Object.entries(group).filter(([k]) => !k.startsWith('$'));
const px = (d) => d.value; // dimensions are {value, unit: px}

function rgba(hex) {
  const h = hex.replace('#', '');
  const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) : 255;
  return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16), a };
}
const hex2 = (n) => n.toString(16).toUpperCase().padStart(2, '0');

const colorNames = leaves(t.color.light).map(([k]) => k);
for (const k of colorNames) if (!t.color.dark[k]) throw new Error(`dark theme is missing color ${k}`);

const typeNames = leaves(t.typography).map(([k]) => k);
const type = (k) => {
  const s = v(t.typography[k]);
  const family = s.fontFamily[0];
  const weight = Number(s.fontWeight);
  const file = family === 'Sora' ? `Sora-${weight === 700 ? 'Bold' : 'SemiBold'}`
    : `DMSans-${weight === 700 ? 'Bold' : weight === 500 ? 'Medium' : 'Regular'}`;
  return { family, weight, file, size: Number(s.fontSize), line: Number(s.lineHeight), tracking: Number(s.letterSpacing) };
};
const fontFiles = ['Sora-SemiBold', 'Sora-Bold', 'DMSans-Regular', 'DMSans-Medium', 'DMSans-Bold'];

const outputs = [];
const emit = (rel, content) => outputs.push({ rel, content });
const copy = (from, rel) => outputs.push({ rel, from });

// ---------- Compose (Android GMS + HMS) ----------
{
  const argb = (hex) => { const c = rgba(hex); return `Color(0x${hex2(c.a)}${hex2(c.r)}${hex2(c.g)}${hex2(c.b)})`; };
  const scheme = (mode) => colorNames.map((k) => `    ${camel(k)} = ${argb(v(t.color[mode][k]))},`).join('\n');
  const androidFont = (f) => f.toLowerCase().replace('dmsans', 'dm_sans').replace('-', '_');
  const weightName = { 400: 'Normal', 500: 'Medium', 600: 'SemiBold', 700: 'Bold' };
  const kt = `// ${HEADER}
package za.co.lifa.design.generated

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import za.co.lifa.design.R

@Immutable
data class LifaColorScheme(
${colorNames.map((k) => `    val ${camel(k)}: Color,`).join('\n')}
)

val LifaLightColors = LifaColorScheme(
${scheme('light')}
)

val LifaDarkColors = LifaColorScheme(
${scheme('dark')}
)

object LifaFonts {
    val Sora = FontFamily(
        Font(R.font.${androidFont('Sora-SemiBold')}, FontWeight.SemiBold),
        Font(R.font.${androidFont('Sora-Bold')}, FontWeight.Bold),
    )
    val DmSans = FontFamily(
        Font(R.font.${androidFont('DMSans-Regular')}, FontWeight.Normal),
        Font(R.font.${androidFont('DMSans-Medium')}, FontWeight.Medium),
        Font(R.font.${androidFont('DMSans-Bold')}, FontWeight.Bold),
    )
}

/** Type scale in sp, so it follows the system font size (NFR-ACC-001). */
object LifaTypeScale {
${typeNames.map((k) => { const s = type(k); return `    val ${camel(k)} = TextStyle(
        fontFamily = LifaFonts.${s.family === 'Sora' ? 'Sora' : 'DmSans'},
        fontWeight = FontWeight.${weightName[s.weight]},
        fontSize = ${s.size}.sp,
        lineHeight = ${s.line}.sp,
        letterSpacing = ${s.tracking < 0 ? `(${s.tracking}).sp` : `${s.tracking}.sp`},
    )`; }).join('\n')}
}

object LifaRadius {
${leaves(t.radius).map(([k, n]) => `    val ${camel(k)} = ${px(v(n))}.dp`).join('\n')}
}

/** 4-point spacing scale: space4 = 16.dp. */
object LifaSpace {
${leaves(t.space).map(([k, n]) => `    val space${k} = ${px(v(n))}.dp`).join('\n')}
}

object LifaSize {
${leaves(t.size).map(([k, n]) => `    val ${camel(k)} = ${px(v(n))}.dp`).join('\n')}
}

object LifaMotion {
${leaves(t.motion).map(([k, n]) => `    const val ${camel(k)}Millis = ${v(n).value}`).join('\n')}
}
`;
  emit('clients/android/core/design/src/main/kotlin/za/co/lifa/design/generated/LifaTokens.kt', kt);
  for (const f of fontFiles) copy(`design/fonts/ttf/${f}.ttf`, `clients/android/core/design/src/main/res/font/${androidFont(f)}.ttf`);
}

// ---------- SwiftUI (iOS) ----------
{
  const rgb = (hex) => { const c = rgba(hex); return `0x${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}, alpha: ${(c.a / 255).toFixed(2)}`; };
  const textStyle = { display: '.largeTitle', 'title-1': '.title', 'title-2': '.title2', 'title-3': '.title3', body: '.body', 'body-strong': '.body', label: '.subheadline', button: '.headline', caption: '.caption', overline: '.caption2' };
  const swift = `// ${HEADER}
import SwiftUI

/// Semantic colours. Each resolves to the light or dark value at render time.
public enum LifaColor {
${colorNames.map((k) => `    public static let ${camel(k)} = Color.lifaDynamic(light: (${rgb(v(t.color.light[k]))}), dark: (${rgb(v(t.color.dark[k]))}))`).join('\n')}
}

/// Type scale. Sizes scale with Dynamic Type relative to the given text style (NFR-ACC-001).
public enum LifaTypography {
${typeNames.map((k) => { const s = type(k); return `    public static let ${camel(k)} = LifaTextStyle(fontName: "${s.file}", size: ${s.size}, lineHeight: ${s.line}, tracking: ${s.tracking}, relativeTo: ${textStyle[k]})`; }).join('\n')}
}

public enum LifaRadius {
${leaves(t.radius).map(([k, n]) => `    public static let ${camel(k)}: CGFloat = ${px(v(n))}`).join('\n')}
}

/// 4-point spacing scale: space4 = 16 pt.
public enum LifaSpace {
${leaves(t.space).map(([k, n]) => `    public static let space${k}: CGFloat = ${px(v(n))}`).join('\n')}
}

public enum LifaSize {
${leaves(t.size).map(([k, n]) => `    public static let ${camel(k)}: CGFloat = ${px(v(n))}`).join('\n')}
}

public enum LifaMotion {
${leaves(t.motion).map(([k, n]) => `    public static let ${camel(k)}: Double = ${(v(n).value / 1000).toFixed(3)}`).join('\n')}
}

/// Bundled font files (PostScript names), registered by LifaFonts.register().
public let lifaFontFiles = [${fontFiles.map((f) => `"${f}"`).join(', ')}]
`;
  emit('clients/ios/LifaDesign/Sources/LifaDesign/Generated/LifaTokens.swift', swift);
  for (const f of fontFiles) copy(`design/fonts/ttf/${f}.ttf`, `clients/ios/LifaDesign/Sources/LifaDesign/Resources/Fonts/${f}.ttf`);
}

// ---------- ArkUI (HarmonyOS NEXT) ----------
{
  const arkHex = (hex) => { const c = rgba(hex); return `#${hex2(c.a)}${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}`; };
  const colorJson = (mode) => JSON.stringify({ color: colorNames.map((k) => ({ name: `lifa_${snake(k)}`, value: arkHex(v(t.color[mode][k])) })) }, null, 2) + '\n';
  emit('clients/harmony/design/src/main/resources/base/element/color.json', colorJson('light'));
  emit('clients/harmony/design/src/main/resources/dark/element/color.json', colorJson('dark'));
  const ets = `// ${HEADER}

/** Semantic colours. Resources switch automatically between base (light) and dark. */
export class LifaColor {
${colorNames.map((k) => `  static readonly ${camel(k)}: Resource = $r('app.color.lifa_${snake(k)}');`).join('\n')}
}

export interface LifaTextStyle {
  fontFamily: string;
  fontWeight: number;
  /** In fp, so it follows the system font size (NFR-ACC-001). */
  fontSize: string;
  lineHeight: string;
  letterSpacing: number;
}

export class LifaTypography {
${typeNames.map((k) => { const s = type(k); return `  static readonly ${camel(k)}: LifaTextStyle = { fontFamily: '${s.file}', fontWeight: ${s.weight}, fontSize: '${s.size}fp', lineHeight: '${s.line}fp', letterSpacing: ${s.tracking} };`; }).join('\n')}
}

export class LifaRadius {
${leaves(t.radius).map(([k, n]) => `  static readonly ${camel(k)}: number = ${px(v(n))};`).join('\n')}
}

/** 4-point spacing scale in vp: space4 = 16. */
export class LifaSpace {
${leaves(t.space).map(([k, n]) => `  static readonly space${k}: number = ${px(v(n))};`).join('\n')}
}

export class LifaSize {
${leaves(t.size).map(([k, n]) => `  static readonly ${camel(k)}: number = ${px(v(n))};`).join('\n')}
}

export class LifaMotion {
${leaves(t.motion).map(([k, n]) => `  static readonly ${camel(k)}: number = ${v(n).value};`).join('\n')}
}

/** Bundled fonts in resources/rawfile/fonts, registered by registerLifaFonts(). */
export const LIFA_FONT_FILES: string[] = [${fontFiles.map((f) => `'${f}'`).join(', ')}];
`;
  emit('clients/harmony/design/src/main/ets/generated/LifaTokens.ets', ets);
  for (const f of fontFiles) copy(`design/fonts/ttf/${f}.ttf`, `clients/harmony/design/src/main/resources/rawfile/fonts/${f}.ttf`);
}

// ---------- CSS (web, back office) ----------
{
  const rem = (n) => `${+(n / 16).toFixed(4)}rem`;
  const vars = (mode) => colorNames.map((k) => `  --lifa-color-${k}: ${v(t.color[mode][k])};`).join('\n');
  const family = (arr) => arr.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ');
  const css = `/* ${HEADER} */
/* Light is the default; dark follows the OS unless data-theme is set on <html>. */
:root {
  color-scheme: light;
${vars('light')}
  --lifa-font-heading: ${family(v(t.font.family.heading))};
  --lifa-font-body: ${family(v(t.font.family.body))};
${typeNames.map((k) => { const s = type(k); return `  --lifa-type-${k}: ${s.weight} ${rem(s.size)}/${rem(s.line)} var(--lifa-font-${s.family === 'Sora' ? 'heading' : 'body'});\n  --lifa-type-${k}-tracking: ${s.tracking}px;`; }).join('\n')}
${leaves(t.radius).map(([k, n]) => `  --lifa-radius-${k}: ${px(v(n))}px;`).join('\n')}
${leaves(t.space).map(([k, n]) => `  --lifa-space-${k}: ${rem(px(v(n)))};`).join('\n')}
${leaves(t.size).map(([k, n]) => `  --lifa-size-${k}: ${px(v(n))}px;`).join('\n')}
${leaves(t.motion).map(([k, n]) => `  --lifa-motion-${k}: ${v(n).value}ms;`).join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${vars('dark').replace(/^/gm, '  ')}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${vars('dark')}
}

${typeNames.map((k) => `.lifa-type-${k} { font: var(--lifa-type-${k}); letter-spacing: var(--lifa-type-${k}-tracking);${k === 'overline' ? ' text-transform: uppercase;' : ''} }`).join('\n')}
`;
  emit('clients/web/src/design/generated/tokens.css', css);
  const faces = fontFiles.map((f) => {
    const [fam, w] = f.split('-');
    const weight = { SemiBold: 600, Bold: 700, Regular: 400, Medium: 500 }[w];
    return `@font-face {\n  font-family: "${fam === 'DMSans' ? 'DM Sans' : 'Sora'}";\n  src: url("/fonts/${f}.woff2") format("woff2");\n  font-weight: ${weight};\n  font-style: normal;\n  font-display: swap;\n}`;
  }).join('\n\n');
  emit('clients/web/src/design/generated/fonts.css', `/* ${HEADER} */\n/* Self-hosted (no Google Fonts at runtime). Glyphs missing from Sora/DM Sans fall back to the next family (D-039). */\n${faces}\n`);
  for (const f of fontFiles) copy(`design/fonts/woff2/${f}.woff2`, `clients/web/public/fonts/${f}.woff2`);
  emit('clients/web/src/design/generated/tokens.ts', `// ${HEADER}\n// Raw values for code that cannot read CSS variables (for example canvas charts).\nexport const lifaColors = ${JSON.stringify({ light: Object.fromEntries(colorNames.map((k) => [camel(k), v(t.color.light[k])])), dark: Object.fromEntries(colorNames.map((k) => [camel(k), v(t.color.dark[k])])) }, null, 2)} as const;\n`);
}

// ---------- write / check ----------
let drift = 0;
for (const o of outputs) {
  const dest = join(ROOT, o.rel);
  const next = o.from ? readFileSync(join(ROOT, o.from)) : Buffer.from(o.content);
  const same = existsSync(dest) && Buffer.compare(readFileSync(dest), next) === 0;
  if (same) continue;
  if (CHECK) { console.error(`drift: ${o.rel}`); drift++; continue; }
  mkdirSync(dirname(dest), { recursive: true });
  if (o.from) copyFileSync(join(ROOT, o.from), dest); else writeFileSync(dest, next);
  console.log(`wrote ${o.rel}`);
}
if (CHECK && drift) { console.error(`${drift} generated file(s) out of date: run npm run tokens:build`); process.exit(1); }
console.log(`${outputs.length} outputs ${CHECK ? 'up to date' : 'built'}; ${colorNames.length} colours × 2 modes, ${typeNames.length} text styles`);
